import { createRouter, createWebHashHistory } from 'vue-router'

// Define routes
const routes = [
  { 
    path: '/', 
    component: () => import('../App.vue'), // Temporary circular reference or placeholder? 
    // Ideally this should point to a Home page generated by the parser. 
    // Since we don't know the generated pages yet, we can't hardcode them easily.
    // But verify if parser generates src/pages/Home/Home_desktop.jsx
  },
  // We can adding a catch-all or dynamic route later
]

const router = createRouter({
  history: createWebHashHistory(),
  routes,
})

export default router
